name: Gersenecksmpplugin
version: '${project.version}'
main: io.github.com.gerseneck.gersenecksmpplugin.GersenecksmppluginMain
api-version: 1.19
authors: [ Gerseneck ]
description: Plugin for Gerseneck Private SMP
