name: Gersenecksmpplugin
version: '${project.version}'
main: io.github.gerseneck.gersenecksmpplugin.GerseneckSmpPluginMain
api-version: 1.19
authors: [ Gerseneck ]
description: Plugin for Gerseneck Private SMP

commands:
  durability:
    description: "Checks the durability of the Item left."
    usage: "Usage: /durability [<hand>, <offhand>, <helmet>, <chestplate>, <leggings>, <boots>]"
    permission: "gersenecksmp.durability"
    permission-message: "ยง4You are not allowed to use this command."
    aliases: [dura, db, d]
  online-players:
    description: "Prints out all the online players."
    usage: "Usage: online-players"
    permission: "gersenecksmp.online-players"
    permission-message: "ยง4You are not allowed to use this command."
    aliases: [online, players, ol, p]
  msg:
    description: "Sends a message to a player."
    usage: "Usage: /msg <player> <message>"
    permission: "gersenecksmp.msg"
    permission-message: "ยง4You are not allowed to use this command."
    aliases: [tell, whisper, w, msg]
  reply:
    description: "Sends a message to the last player you messaged."
    usage: "Usage: /reply <message>"
    permission: "gersenecksmp.msg"
    permission-message: "ยง4You are not allowed to use this command."
    aliases: [r]

permissions:
  gersenecksmp.durability:
    default: true
  gersenecksmp.online-players:
    default: true
  gersenecksmp.msg:
      default: true